#!/bin/bash -l
# Batch script to run 1 ABM on 1 core

# 1. Force bash as the executing shell.
#$ -S /bin/bash

# 2. Request one hour of wallclock time (format hours:minutes:seconds).
#$ -l h_rt=20:00:00

# 5. Set the name of the job.
#$ -N bigtrust

#$ -cwd

#$ -pe mpi 1

python TrustModelFindGossip.py standard_input
