#!/bin/bash -l
# Batch script to run 1 ABM on 1 core

# 1. Force bash as the executing shell.
#$ -S /bin/bash

# 2. Request one hour of wallclock time (format hours:minutes:seconds).
#$ -l h_rt=3:00:00

# 5. Set the name of the job.
#$ -N trust

#$ -cwd

#$ -q cdt.7.day

#$ -pe mpi 1

python TrustModel.py standard_input
